name: camera_camera
description: The easy plugin camera for your project, platforms Android and iOS.
version: 3.0.1
repository: https://github.com/tomquas/camera_camera
publish_to:

environment:
  sdk: ">=2.12.0-0.0 <4.0.0"

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:

